name: check tasks

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir test
      - uses: actions/checkout@v3
        with:
          path: ./test
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: build
        working-directory: test
        run: |
          go get -u "github.com/szpp-judge-contests/template-contest/task"
          go env -w GO111MODULE=auto
          go build -o ./.. ./.cicd/check_task
      - name: check tasks
        run: ./check_task
