name: check tasks

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: build
      env:
          TASKS_ROOT: "."
        working-directory: test
        run: go build -o ./.. ./check_task
      - name: check tasks
        run: ./check_task
