name: check tasks

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir test
      - uses: actions/checkout@v3
        with:
          path: ./test
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: ls -la ./.cicd/
        working-directory: test
      - run: go env -w GO111MODULE=auto
      - name: build
        working-directory: test
        run: go build -o ./.. ./.cicd/
      - name: check tasks
        run: ./check_task
